version: "3.7"

services:
  api:
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./api/.env
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=video_instructor
      - POSTGRES_USER=caleb
      - POSTGRES_PASSWORD=admin

  client:
    build: ./client
    ports:
      - 4200:80
    depends_on:
      - api

volumes:
  postgres_data:
